services:
  ingestion:
    build: ./simple_ingestion
    container_name: ingestion
    profiles: ["ingest"]
    volumes:
      - ./data:/data
    environment:
      AWS_S3_ENDPOINT: http://minio:9000
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minioadmin
    depends_on:
      - minioserver

  dremio:
    platform: linux/x86_64
    image: dremio/dremio-oss:latest
    ports:
      - "9047:9047"
      - "31010:31010"
      - "32010:32010"
    container_name: dremio
    volumes:
      - dremio_data:/opt/dremio/data

  minioserver:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    container_name: minio
    command: server /data --console-address ":9001"

  nessie:
    image: projectnessie/nessie
    container_name: nessie
    ports:
      - "19120:19120"

  superset:
    build: ./docker/superset
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      SUPERSET_WEBSERVER_PORT: 8088
      SUPERSET_ADMIN_PASSWORD: admin
      SUPERSET_SECRET_KEY: xxxxx
    volumes:
      - ./superset:/app/superset_home
      - ./superset-init.sh:/app/superset-init.sh
    entrypoint: /app/superset-init.sh
    user: root

  jupyterlab:
    image: jupyter/datascience-notebook:latest
    container_name: jupyterlab
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jovyan/work
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      GRANT_SUDO: "yes"
    command: start-notebook.sh --NotebookApp.token=''

networks:
  default:
    name: lakehousenet
    driver: bridge

volumes:
  dremio_data:
  minio_data:
  nessie_data:
